### ISSUE TITLE
Country patent types [FTR#3]

### ISSUE THREAD

**Issue by EliaPaccagnella** [EliaPaccagnella/Patents_carbonara#3]
# Country patent types [FTR#3]

##Task:

Write a function that implements FTR #3: "Country patent types".

The function must generate a graph that makes it easy to visualize the top n patent types within a country.

## Assignee:

- @GiacomoVettore

**Comment by GiacomoVettore** [comment]
We'll close the issue as the database doesn't allow us to make a meaningful statistical research of this type, as the vast majority of patents are all under the same category.
